### PR TITLE
feat: better raw footage

### PR DESCRIPTION
**Pull request by emonadeo**
Going forward, store raw footage in a dedicated column in `record_notes`, and render it as a clickable link in the record notes seen in the List Integration tab and Records tab.

Probably obsoletes #67.

### CODE REVIEW

**Comment by emonadeo** [comment]
WIP, `record_notes_modifications` is not supported yet.

Attaching the raw footage to the notes means there can be multiple raw footage links (because there can be multiple notes), but I might reconsider this choice and add the column directly to the `records` table instead. Thoughts on this?

**Comment by stadust** [comment]
> WIP, `record_notes_modifications` is not supported yet.
> 
> Attaching the raw footage to the notes means there can be multiple raw footage links (because there can be multiple notes), but I might reconsider this choice and add the column directly to the `records` table instead. Thoughts on this?

I think adding a new field makes more sense, the record submitter doesn't allow submitting multiple raw footage fields anyway. So just handling it similar to the verification video is what we should go for.

**Comment by emonadeo** [comment]
Reworked so raw footage lives on the record table. However, this also exposes raw footage links to unauthorized users :/

**Comment by emonadeo** [comment]
Screenshot 2024-07-30 at 05 06 13

**Comment by stadust** [comment]
> Reworked so raw footage lives on the record table. However, this also exposes raw footage links to unauthorized users :/

There's already some logic in the record handler that sets the submitter object to `None` for unauthorized requests, we can do the same for raw footage (and then add some integration tests that it really doesn't leak anything xP)

**Comment by emonadeo** [comment]
not a big fan of the flow of pulling all data from the db, and then filtering out the sensitive stuff. it does feel very prone to accidentally leaking information, but reworking this would be pretty major effort with diminishing return (ideally you only ever get the data you are authorized to get).

will implement as suggested.

**Comment by emonadeo** [comment]
done I think

**Comment by stadust** [comment]
> done I think

thanks! I've pushed a commit to change the test slightly to avoid making the fields of `Submission` public. Will merge once CI is done :)

**Comment by stadust** [comment]
> not a big fan of the flow of pulling all data from the db, and then filtering out the sensitive stuff. it does feel very prone to accidentally leaking information, but reworking this would be pretty major effort with diminishing return (ideally you only ever get the data you are authorized to get).

For what it's worth btw, I don't think it'd be a huge effort to overhaul this - we can just have two structs, similar to `User` and `AuthenticatedUser`, and then all the `GET` endpoints would have to return some sort of `Either` thingy, I guess. If you wanna go for it, I'd accept a PR for it

**Pull request merged**
